default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      pass: password
      port: 5432
      dbname: demo
      schema: public
      threads: 8
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 100 # default 10 seconds
